### ISSUE TITLE
解决界面会灰一下然后立刻变回去的问题（可能对其他非更新提示的弹窗有影响）

### ISSUE THREAD

**Issue by SauerkrautF1sh** [xh321/BetterQQNT-Kill-Update#1]
通过您开发的自定义css样式的插件，直接在`q-dialog`选择器下添加`display: none!important;`属性，即可解决界面会灰一下然后立刻变回去的问题。但是同时也会使得其他弹窗无法弹出，在不确定是否有其他非更新提示的弹窗的情况下，可能因此造成一些影响。
> 暂时还在思考如何通过插件而不是修改css的形式防弹窗＞﹏＜
```css
.q-dialog{
    display: none!important;
}
```
